spring:
  application:
    name: wedding-planner-backend

#  datasource:
#    url: jdbc:h2:file:./database/wedding-planner
#    username: sa
#    password: password
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: WEDDING_PLANNER
    password: passw0rd
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    contexts: local

wedding-planner:
  security:
    jwt:
      secret-key: 0deb14ea7ac92f72d4ea3d4570832ae4ac49a929dd56bcc037de68c584125ddb
